name: mftransformer
dependencies:
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- py=1.4.31=py35_0
- pytest=2.9.1=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=21.2.1=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3

